export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function DashboardLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <div>
          <h1>dashboard</h1>
          {children}
        </div>
    )
  }
  