'use client'
import { usePathname } from "next/navigation"
import { Fragment } from "react"
import Navbar from "../../components/common/Navbar"
import Footer from "../../components/common/Footer"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function PersonalLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
